language: go

go:
- 1.13.x

env:
- GO111MODULE=on

git:
  depth: 1

notifications:
  email: false

script:
  - go get -t -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./analysis

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: sudo apt-get -y install upx-ucl && curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux