language: go

go:
- 1.15.x

env:
- GO111MODULE=on

git:
  depth: 1

branches:
  only:
  - master

cache:
  directories:
    - $GOPATH/pkg/mod

notifications:
  email: false

before_install:
  - sudo apt-get -y install libleveldb-dev
  # - ./scripts/build_leveldb.sh

script:
  - go get -t -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

# deploy:
# - provider: script
#   skip_cleanup: true
#   script: curl -sL https://git.io/goreleaser | bash
#   on:
#     tags: true
#     condition: $TRAVIS_OS_NAME = linux